package cn.safetyledger.app;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import cn.safetyledger.app.data.Entities.*;import cn.safetyledger.app.data.LedgerRepository;import cn.safetyledger.app.pdf.PdfExporter;import java.io.*;import java.time.*;import java.time.temporal.TemporalAdjusters;import java.util.*;

public final class LedgerActivity extends Activity{
    private static final int EXPORT=701;private LedgerRepository repo;private LinearLayout records,calendarBox,selectionActions;private TextView monthTitle,pageTitle;private Spinner range,type,statusFilter,pageSize;private Button multiToggle;private boolean multiMode=false;private YearMonth month=YearMonth.now();private String selectedDate;private int page=1,total=0,size=10;private final Set<String>selected=new LinkedHashSet<>();private List<Inspection>current=new ArrayList<>(),exportRecords;
    @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new LedgerRepository(this);render();load();}
    private void render(){LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.BG);LinearLayout bar=Ui.row(this);bar.setBackgroundColor(Ui.DARK);TextView back=Ui.text(this,"‹",34,true);back.setTextColor(Color.WHITE);back.setOnClickListener(v->finish());TextView title=Ui.text(this,"安全检查台账",21,true);title.setTextColor(Color.WHITE);Button form=Ui.button(this,"检查填报");form.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));Button settings=Ui.button(this,"设置");settings.setOnClickListener(v->Ui.start(this,SettingsActivity.class));bar.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,56)));bar.addView(title,Ui.weight(1));bar.addView(settings);bar.addView(form);root.addView(bar);
        LinearLayout mr=Ui.row(this);Button prev=Ui.button(this,"上个月"),next=Ui.button(this,"下个月");monthTitle=Ui.text(this,"",19,true);monthTitle.setGravity(Gravity.CENTER);prev.setOnClickListener(v->{month=month.minusMonths(1);selectedDate=null;syncCalendar();load();});next.setOnClickListener(v->{month=month.plusMonths(1);selectedDate=null;syncCalendar();load();});mr.addView(prev);mr.addView(monthTitle,Ui.weight(1));mr.addView(next);root.addView(mr);calendarBox=Ui.column(this);root.addView(calendarBox);syncCalendar();
        LinearLayout filters=Ui.row(this);range=spinner(new String[]{"当日","本月","本季度","本年度","全部"});type=spinner(types());statusFilter=spinner(new String[]{"全部状态","待整改","整改中","已整改完成","已完成"});pageSize=spinner(new String[]{"10条/页","20条/页","50条/页","100条/页","200条/页"});range.setSelection(1);AdapterView.OnItemSelectedListener l=new SimpleSelect(){void selected(){page=1;load();}};range.setOnItemSelectedListener(l);type.setOnItemSelectedListener(l);statusFilter.setOnItemSelectedListener(l);pageSize.setOnItemSelectedListener(new SimpleSelect(){void selected(){int[]s={10,20,50,100,200};size=s[pageSize.getSelectedItemPosition()];page=1;load();}});filters.addView(range,Ui.weight(1));filters.addView(type,Ui.weight(1));filters.addView(statusFilter,Ui.weight(1));filters.addView(pageSize,Ui.weight(1));root.addView(filters);
        multiToggle=Ui.button(this,"多选导出");multiToggle.setOnClickListener(v->{multiMode=!multiMode;if(!multiMode)selected.clear();multiToggle.setText(multiMode?"退出多选导出":"多选导出");selectionActions.setVisibility(multiMode?View.VISIBLE:View.GONE);showRecords();});root.addView(multiToggle);selectionActions=Ui.row(this);Button all=Ui.button(this,"全选筛选结果"),none=Ui.button(this,"取消全选"),export=Ui.button(this,"导出选中"),period=Ui.button(this,"导出当前周期");all.setOnClickListener(v->selectAll());none.setOnClickListener(v->{selected.clear();showRecords();});export.setOnClickListener(v->exportSelected());period.setOnClickListener(v->{selected.clear();exportSelected();});selectionActions.addView(all,Ui.weight(1));selectionActions.addView(none,Ui.weight(1));selectionActions.addView(export,Ui.weight(1));selectionActions.addView(period,Ui.weight(1));selectionActions.setVisibility(View.GONE);root.addView(selectionActions);
        ScrollView sv=new ScrollView(this);records=Ui.column(this);records.setPadding(Ui.dp(this,10),Ui.dp(this,5),Ui.dp(this,10),Ui.dp(this,10));sv.addView(records);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout pager=Ui.row(this);Button p=Ui.button(this,"上一页"),n=Ui.button(this,"下一页");pageTitle=Ui.text(this,"",15,true);pageTitle.setGravity(Gravity.CENTER);p.setOnClickListener(v->{if(page>1){page--;load();}});n.setOnClickListener(v->{if(page*size<total){page++;load();}});pager.addView(p);pager.addView(pageTitle,Ui.weight(1));pager.addView(n);root.addView(pager);setContentView(root);}
    private abstract class SimpleSelect implements AdapterView.OnItemSelectedListener{public void onItemSelected(AdapterView<?>a,View v,int p,long id){selected();}public void onNothingSelected(AdapterView<?>a){}abstract void selected();}
    private Spinner spinner(String[]values){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));return s;}
    private String[]types(){List<String>o=new ArrayList<>();o.add("全部类型");for(Template t:repo.templates(true))if(!o.contains(t.category))o.add(t.category);return o.toArray(new String[0]);}
    private void syncCalendar(){monthTitle.setText(String.format(Locale.CHINA,"%d年%d月",month.getYear(),month.getMonthValue()));calendarBox.removeAllViews();GridLayout grid=new GridLayout(this);grid.setColumnCount(7);String[]weeks={"一","二","三","四","五","六","日"};for(String w:weeks){TextView h=Ui.text(this,w,14,true);h.setGravity(Gravity.CENTER);grid.addView(h,new GridLayout.LayoutParams(GridLayout.spec(GridLayout.UNDEFINED,1,1f),GridLayout.spec(GridLayout.UNDEFINED,1,1f)));}Set<String>inspections=repo.markedDates(month.toString());Map<String,String[]>holidays=repo.holidays(month.toString());int leading=month.atDay(1).getDayOfWeek().getValue()-1;for(int i=0;i<leading;i++)grid.addView(Ui.text(this,"",14,false),cellParams());for(int day=1;day<=month.lengthOfMonth();day++){LocalDate date=month.atDay(day);String key=date.toString();String[]holiday=holidays.get(key);TextView cell=Ui.text(this,String.valueOf(day),15,inspections.contains(key));cell.setGravity(Gravity.CENTER);cell.setMinHeight(Ui.dp(this,42));int color=Color.WHITE;if(holiday!=null)color="WORKDAY".equals(holiday[1])?0xffffedd5:0xffffe4e6;if(inspections.contains(key))color=0xffa5f3fc;if(key.equals(selectedDate))color=0xfffef08a;cell.setBackground(Ui.border(this,color==Color.WHITE?0xffcbd5e1:color));cell.setBackgroundColor(color);cell.setContentDescription(key+(holiday==null?"":" "+holiday[0])+(inspections.contains(key)?" 有检查记录":""));cell.setOnClickListener(v->{selectedDate=key;range.setSelection(0);page=1;syncCalendar();load();});grid.addView(cell,cellParams());}calendarBox.addView(grid);TextView legend=Ui.text(this,"蓝色：有检查  红色：法定假日  橙色：调休上班  黄色：当前选择",12,false);calendarBox.addView(legend);}
    private GridLayout.LayoutParams cellParams(){GridLayout.LayoutParams p=new GridLayout.LayoutParams(GridLayout.spec(GridLayout.UNDEFINED,1,1f),GridLayout.spec(GridLayout.UNDEFINED,1,1f));p.width=0;p.height=Ui.dp(this,44);p.setMargins(1,1,1,1);return p;}
    private String[]bounds(){LocalDate today=selectedDate==null?LocalDate.now():LocalDate.parse(selectedDate);int r=range==null?1:range.getSelectedItemPosition();if(r==0)return new String[]{today.toString(),today.toString()};if(r==1){LocalDate a=month.atDay(1);return new String[]{a.toString(),a.with(TemporalAdjusters.lastDayOfMonth()).toString()};}if(r==2){int sm=((today.getMonthValue()-1)/3)*3+1;LocalDate a=LocalDate.of(today.getYear(),sm,1);return new String[]{a.toString(),a.plusMonths(2).with(TemporalAdjusters.lastDayOfMonth()).toString()};}if(r==3)return new String[]{LocalDate.of(today.getYear(),1,1).toString(),LocalDate.of(today.getYear(),12,31).toString()};return new String[]{null,null};}
    private String selectedStatus(){if(statusFilter==null||statusFilter.getSelectedItemPosition()==0)return null;return new String[]{null,"PENDING_RECTIFICATION","RECTIFYING","RECTIFIED","COMPLETED"}[statusFilter.getSelectedItemPosition()];}
    private void load(){if(records==null)return;String[]b=bounds();String ty=type==null||type.getSelectedItemPosition()==0?null:(String)type.getSelectedItem();Page<Inspection>p=repo.list(b[0],b[1],ty,selectedStatus(),false,page,size);current=p.rows;total=p.total;showRecords();}
    private void showRecords(){records.removeAllViews();Set<String>marks=repo.markedDates(month.toString());if(!marks.isEmpty())records.addView(Ui.text(this,"本月有检查："+String.join("、",marks),13,true));Map<String,String[]>hs=repo.holidays(month.toString());if(hs.isEmpty())records.addView(Ui.text(this,"本年度法定节假日尚未正式公布或未缓存（不进行预测）",13,true));else{List<String>labels=new ArrayList<>();for(Map.Entry<String,String[]>e:hs.entrySet())labels.add(e.getKey().substring(5)+" "+e.getValue()[0]+("WORKDAY".equals(e.getValue()[1])?"（调休上班）":""));Collections.sort(labels);records.addView(Ui.text(this,"国务院正式安排："+String.join("、",labels),12,false));}for(Inspection x:current){LinearLayout row=Ui.row(this);CheckBox c=new CheckBox(this);c.setVisibility(multiMode?View.VISIBLE:View.GONE);c.setChecked(selected.contains(x.id));c.setOnCheckedChangeListener((b,on)->{if(on)selected.add(x.id);else selected.remove(x.id);pageTitle.setText(String.format(Locale.CHINA,"第 %d 页 · 共 %d 条 · 已选 %d 条",page,total,selected.size()));});TextView t=Ui.text(this,x.date+" "+x.time+" · "+x.templateName+"\n"+x.location+" · "+status(x.status),16,false);t.setOnClickListener(v->{if(multiMode)c.setChecked(!c.isChecked());else startActivity(new Intent(this,RecordDetailActivity.class).putExtra("inspection_id",x.id));});row.setBackground(Ui.border(this,0xffcbd5e1));row.addView(c);row.addView(t,Ui.weight(1));records.addView(row);records.addView(Ui.gap(this,6));}pageTitle.setText(String.format(Locale.CHINA,"第 %d 页 · 共 %d 条 · 已选 %d 条",page,total,selected.size()));}
    private void selectAll(){String[]b=bounds();String ty=type.getSelectedItemPosition()==0?null:(String)type.getSelectedItem();for(Inspection x:repo.list(b[0],b[1],ty,selectedStatus(),false,1,100000).rows)selected.add(x.id);showRecords();}
    private void exportSelected(){exportRecords=new ArrayList<>();if(selected.isEmpty()){String[]b=bounds();String ty=type.getSelectedItemPosition()==0?null:(String)type.getSelectedItem();for(Inspection x:repo.list(b[0],b[1],ty,selectedStatus(),false,1,100000).rows)exportRecords.add(repo.inspection(x.id));}else for(String id:selected){Inspection x=repo.inspection(id);if(x!=null)exportRecords.add(x);}if(exportRecords.isEmpty()){Ui.toast(this,"没有可导出的检查记录");return;}startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/pdf").putExtra(Intent.EXTRA_TITLE,"安全检查台账-"+LocalDate.now()+".pdf"),EXPORT);}
    @Override protected void onActivityResult(int r,int ok,Intent d){super.onActivityResult(r,ok,d);if(r==EXPORT&&ok==RESULT_OK&&d!=null)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){new PdfExporter(this).export(exportRecords,o);Ui.toast(this,"已生成 A4 PDF，共 "+exportRecords.size()+" 条记录");}catch(Exception e){Ui.toast(this,"PDF 导出失败："+e.getMessage());}}
    private String status(String s){return switch(s){case"PENDING_RECTIFICATION"->"待整改";case"RECTIFYING"->"整改中";case"RECTIFIED"->"已整改完成";case"COMPLETED"->"已完成";default->"草稿";};}
    @Override protected void onResume(){super.onResume();if(records!=null)load();}
}
