package cn.safetyledger.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.BitmapFactory;
import android.location.*;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import cn.safetyledger.app.data.Entities.*;
import cn.safetyledger.app.data.LedgerRepository;
import cn.safetyledger.app.media.MediaService;
import java.io.File;
import java.time.LocalDate;
import java.util.*;

public class MainActivity extends Activity {
    private static final int CAMERA=501,GALLERY=502,SIGN=503,PERMS=504;
    private LedgerRepository repo; private Inspection model; private LinearLayout itemsBox,mediaBox; private final Map<String,EditText> fields=new HashMap<>(),problemFields=new HashMap<>();private Uri cameraUri;private String pendingCategory="SCENE",pendingItemId;
    @Override protected void onCreate(Bundle state){super.onCreate(state);repo=new LedgerRepository(this);String id=getIntent().getStringExtra("inspection_id");if(id==null)id=repo.setting("current_draft","");model=id.isBlank()?null:repo.inspection(id);if(model==null||model.deletedAt!=null||!"DRAFT".equals(model.status)){List<Template>ts=repo.templates(false);if(ts.isEmpty()){Ui.toast(this,"请先新建并启用检查模板");Ui.start(this,TemplateActivity.class);finish();return;}chooseTemplate(ts);return;}render();}
    private void chooseTemplate(List<Template> templates){String[]names=new String[templates.size()];for(int i=0;i<names.length;i++)names[i]=templates.get(i).name+" · "+templates.get(i).category;new AlertDialog.Builder(this).setTitle("选择基础设施 / 检查模板").setCancelable(false).setItems(names,(d,which)->{model=repo.newInspection(templates.get(which).id);repo.putSetting("current_draft",model.id);render();}).setNeutralButton("模板管理",(d,w)->{Ui.start(this,TemplateActivity.class);finish();}).show();}
    private void render(){ScrollView sv=new ScrollView(this);LinearLayout root=Ui.column(this);root.setPadding(Ui.dp(this,12),Ui.dp(this,10),Ui.dp(this,12),Ui.dp(this,30));root.setBackgroundColor(Ui.BG);
        LinearLayout top=Ui.row(this);TextView title=Ui.text(this,model.templateName+"记录表",24,true);top.addView(title,Ui.weight(1));Button ledger=Ui.button(this,"台账中心");ledger.setOnClickListener(v->Ui.start(this,LedgerActivity.class));top.addView(ledger);root.addView(top);root.addView(Ui.gap(this,8));
        LinearLayout nav=Ui.row(this);for(Object[]x:new Object[][]{{"切换模板",TemplateActivity.class},{"设置/备份",SettingsActivity.class}}){Button b=Ui.button(this,(String)x[0]);b.setOnClickListener(v->Ui.start(this,(Class<?>)x[1]));nav.addView(b,Ui.weight(1));}root.addView(nav);root.addView(Ui.gap(this,12));
        addField(root,"检查日期",model.date,"date");addField(root,"检查时间",model.time,"time");addField(root,"检查类型",model.type,"type");addField(root,"被检查单位",model.unit,"unit");addField(root,"检查地点",model.location,"location");addField(root,"值班人员",model.onDuty,"onDuty");addField(root,"检查人员1",model.inspector1,"inspector1");addField(root,"检查人员2",model.inspector2,"inspector2");addField(root,"被检查人",model.inspectee,"inspectee");
        TextView h=Ui.text(this,"检查类别 / 检查内容及标准 / 检查结果",18,true);h.setBackgroundColor(0xffdbeafe);root.addView(h);itemsBox=Ui.column(this);root.addView(itemsBox);renderItems();
        addField(root,"检查结论",model.conclusion,"conclusion");addField(root,"整改意见",model.advice,"advice");addField(root,"整改责任人",model.responsible,"responsible");addField(root,"整改期限",model.deadline,"deadline");
        TextView ph=Ui.text(this,"现场照片（自动水印时间、地点及可用经纬度）",18,true);root.addView(ph);LinearLayout pics=Ui.row(this);Button cam=Ui.button(this,"拍摄现场照片");Button gal=Ui.button(this,"从相册选择");cam.setOnClickListener(v->capture("SCENE",null));gal.setOnClickListener(v->pick("SCENE",null));pics.addView(cam,Ui.weight(1));pics.addView(gal,Ui.weight(1));root.addView(pics);mediaBox=Ui.column(this);root.addView(mediaBox);renderMedia();
        TextView sh=Ui.text(this,"三方电子签名",18,true);root.addView(sh);LinearLayout signs=Ui.row(this);for(String r:new String[]{"INSPECTOR1","INSPECTOR2","INSPECTEE"}){Button b=Ui.button(this,r.equals("INSPECTOR1")?"检查人1签名":r.equals("INSPECTOR2")?"检查人2签名":"被检查人签名");b.setOnClickListener(v->sign(r));signs.addView(b,Ui.weight(1));}root.addView(signs);
        Button save=Ui.button(this,"保存检查记录");save.setTextSize(18);save.setOnClickListener(v->save());root.addView(Ui.gap(this,18));root.addView(save);sv.addView(root);setContentView(sv);}
    private void addField(LinearLayout root,String label,String value,String key){LinearLayout r=Ui.row(this);TextView l=Ui.text(this,label,16,true);EditText e=Ui.input(this,"请输入"+label);e.setText(value);fields.put(key,e);r.addView(l,new LinearLayout.LayoutParams(Ui.dp(this,112),-2));r.addView(e,Ui.weight(1));root.addView(r);}
    private void renderItems(){itemsBox.removeAllViews();problemFields.clear();for(InspectionItem item:model.items){LinearLayout card=Ui.column(this);card.setPadding(Ui.dp(this,8),Ui.dp(this,6),Ui.dp(this,8),Ui.dp(this,8));card.setBackground(Ui.border(this,0xffcbd5e1));TextView c=Ui.text(this,item.order+". "+item.category,17,true);card.addView(c);card.addView(Ui.text(this,item.content,16,false));TextView std=Ui.text(this,"标准："+item.standard,14,false);std.setTextColor(0xff475569);card.addView(std);RadioGroup rg=new RadioGroup(this);rg.setOrientation(RadioGroup.HORIZONTAL);String[]vs={"PASS","FAIL","NA"},names={"合格","不合格","不适用"};for(int i=0;i<3;i++){RadioButton b=new RadioButton(this);b.setText(names[i]);b.setTag(vs[i]);rg.addView(b,Ui.weight(1));if(vs[i].equals(item.result))b.setChecked(true);}EditText problem=Ui.input(this,"现场问题（选择不合格时必填）");problem.setText(item.problem);problemFields.put(item.id,problem);problem.setVisibility("FAIL".equals(item.result)?View.VISIBLE:View.GONE);LinearLayout photo=Ui.row(this);Button cam=Ui.button(this,"拍问题照片");Button gal=Ui.button(this,"选问题照片");cam.setOnClickListener(v->capture("PROBLEM",item.id));gal.setOnClickListener(v->pick("PROBLEM",item.id));photo.addView(cam,Ui.weight(1));photo.addView(gal,Ui.weight(1));photo.setVisibility(problem.getVisibility());rg.setOnCheckedChangeListener((g,checked)->{RadioButton b=g.findViewById(checked);if(b!=null){item.result=(String)b.getTag();boolean bad="FAIL".equals(item.result);problem.setVisibility(bad?View.VISIBLE:View.GONE);photo.setVisibility(bad?View.VISIBLE:View.GONE);}});card.addView(rg);card.addView(problem);card.addView(photo);itemsBox.addView(card);itemsBox.addView(Ui.gap(this,8));}}
    private void capture(String cat,String item){pendingCategory=cat;pendingItemId=item;if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA,Manifest.permission.ACCESS_FINE_LOCATION},PERMS);return;}ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"inspection-"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);startActivityForResult(i,CAMERA);}
    private void pick(String cat,String item){pendingCategory=cat;pendingItemId=item;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),GALLERY);}
    private void sign(String role){startActivityForResult(new Intent(this,SignatureActivity.class).putExtra("inspection_id",model.id).putExtra("role",role),SIGN);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK)return;if(req==CAMERA&&cameraUri!=null){importPhoto(cameraUri);getContentResolver().delete(cameraUri,null,null);}else if(req==GALLERY&&data!=null&&data.getData()!=null)importPhoto(data.getData());else if(req==SIGN)Ui.toast(this,"签名已保存");}
    @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==PERMS&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)capture(pendingCategory,pendingItemId);}
    private Location lastLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return null;LocationManager lm=getSystemService(LocationManager.class);Location best=null;for(String p:lm.getProviders(true)){Location x=lm.getLastKnownLocation(p);if(x!=null&&(best==null||x.getAccuracy()<best.getAccuracy()))best=x;}return best;}
    private void importPhoto(Uri u){syncFields();try{Media m=new MediaService(this).importAndWatermark(u,model.id,pendingItemId,pendingCategory,model.location,lastLocation());repo.addMedia(m);model.media.add(m);renderMedia();Ui.toast(this,"照片已保存并加水印");}catch(Exception e){Ui.toast(this,"照片处理失败："+e.getMessage());}}
    private void renderMedia(){mediaBox.removeAllViews();for(Media m:repo.media(model.id)){LinearLayout r=Ui.row(this);ImageView iv=new ImageView(this);iv.setScaleType(ImageView.ScaleType.CENTER_CROP);iv.setImageBitmap(BitmapFactory.decodeFile(m.localPath));r.addView(iv,new LinearLayout.LayoutParams(Ui.dp(this,88),Ui.dp(this,72)));r.addView(Ui.text(this,("PROBLEM".equals(m.category)?"问题照片":"现场照片")+"\n"+new File(m.localPath).getName(),14,false),Ui.weight(1));mediaBox.addView(r);}}
    private void syncFields(){model.date=val("date");model.time=val("time");model.type=val("type");model.unit=val("unit");model.location=val("location");model.onDuty=val("onDuty");model.inspector1=val("inspector1");model.inspector2=val("inspector2");model.inspectee=val("inspectee");model.conclusion=val("conclusion");model.advice=val("advice");model.responsible=val("responsible");model.deadline=val("deadline");for(InspectionItem item:model.items){EditText e=problemFields.get(item.id);if(e!=null)item.problem=e.getText().toString().trim();}}
    private String val(String k){return fields.get(k).getText().toString().trim();}
    private void save(){syncFields();boolean incomplete=false,bad=false;for(InspectionItem x:model.items){if("UNSET".equals(x.result))incomplete=true;if("FAIL".equals(x.result)){bad=true;if(x.problem.isBlank())x.problem="详见现场问题及照片";}}if(incomplete){Ui.toast(this,"请完成每一项检查结果");return;}if(model.location.isBlank()){Ui.toast(this,"请填写检查地点");return;}model.status=bad?"PENDING_RECTIFICATION":"COMPLETED";if(model.conclusion.isBlank())model.conclusion=bad?"检查发现问题，进入整改闭环":"本次检查项目符合要求";repo.saveInspection(model);repo.putSetting("current_draft","");Ui.toast(this,bad?"已保存，状态：待整改":"已保存，状态：已完成");startActivity(new Intent(this,RecordDetailActivity.class).putExtra("inspection_id",model.id));finish();}
}
