package cn.safetyledger.app;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.BitmapFactory;import android.net.Uri;import android.os.Bundle;import android.provider.MediaStore;import android.view.*;import android.widget.*;import cn.safetyledger.app.data.Entities.*;import cn.safetyledger.app.data.LedgerRepository;import cn.safetyledger.app.media.MediaService;import cn.safetyledger.app.pdf.PdfExporter;import java.io.*;import java.util.*;

public final class RecordDetailActivity extends Activity{
    private static final int PICK=610,PDF=611,CAMERA=612,PERMISSION=613;private LedgerRepository repo;private Inspection model;private LinearLayout media;private EditText rectification,recheck;private String photoCategory="RECTIFICATION";private Uri cameraUri;
    @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new LedgerRepository(this);model=repo.inspection(getIntent().getStringExtra("inspection_id"));if(model==null){finish();return;}render();}
    private void render(){ScrollView sv=new ScrollView(this);LinearLayout root=Ui.column(this);root.setPadding(Ui.dp(this,12),0,Ui.dp(this,12),Ui.dp(this,30));LinearLayout bar=Ui.row(this);TextView back=Ui.text(this,"‹",34,true);back.setOnClickListener(v->finish());TextView title=Ui.text(this,"检查记录详情",21,true);bar.setBackgroundColor(Ui.DARK);back.setTextColor(0xffffffff);title.setTextColor(0xffffffff);bar.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,52),Ui.dp(this,56)));bar.addView(title,Ui.weight(1));root.addView(bar);root.addView(Ui.text(this,model.templateName+"\n"+model.date+" "+model.time+"  "+model.location,20,true));root.addView(Ui.text(this,"状态："+status(model.status),17,true));for(InspectionItem x:model.items){TextView v=Ui.text(this,x.order+". "+x.category+" · "+result(x.result)+"\n"+x.content+(x.problem.isBlank()?"":"\n问题："+x.problem),15,false);v.setBackground(Ui.border(this,0xffcbd5e1));root.addView(v);root.addView(Ui.gap(this,5));}root.addView(Ui.text(this,"检查结论："+model.conclusion+"\n整改意见："+model.advice+"\n责任人："+model.responsible+"  期限："+model.deadline,15,false));rectification=Ui.input(this,"填写整改情况");rectification.setText(model.rectification);root.addView(Ui.text(this,"整改情况",17,true));root.addView(rectification);root.addView(photoButtons("整改照片","RECTIFICATION"));recheck=Ui.input(this,"填写复查结果");recheck.setText(model.recheck);root.addView(Ui.text(this,"复查结果",17,true));root.addView(recheck);root.addView(photoButtons("复查照片","RECHECK"));media=Ui.column(this);root.addView(media);showMedia();
        LinearLayout st=Ui.row(this);for(String[]x:new String[][]{{"整改中","RECTIFYING"},{"已整改完成","RECTIFIED"},{"复查完成","COMPLETED"}}){Button bt=Ui.button(this,x[0]);bt.setOnClickListener(v->saveStatus(x[1]));st.addView(bt,Ui.weight(1));}root.addView(st);Button pdf=Ui.button(this,"导出本条 A4 PDF");pdf.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/pdf").putExtra(Intent.EXTRA_TITLE,"安全检查记录-"+model.date+".pdf"),PDF));root.addView(pdf);Button del=Ui.button(this,"移入回收站");del.setOnClickListener(v->{repo.softDelete(model.id);Ui.toast(this,"已移入回收站");finish();});root.addView(del);sv.addView(root);setContentView(sv);}
    private LinearLayout photoButtons(String label,String category){LinearLayout row=Ui.row(this);Button camera=Ui.button(this,"拍摄"+label),gallery=Ui.button(this,"选择"+label);camera.setOnClickListener(v->capture(category));gallery.setOnClickListener(v->pick(category));row.addView(camera,Ui.weight(1));row.addView(gallery,Ui.weight(1));return row;}
    private void saveStatus(String s){model.rectification=rectification.getText().toString().trim();model.recheck=recheck.getText().toString().trim();if(("RECTIFIED".equals(s)||"COMPLETED".equals(s))&&model.rectification.isBlank()){Ui.toast(this,"请先填写整改情况");return;}if("COMPLETED".equals(s)&&model.recheck.isBlank()){Ui.toast(this,"请先填写复查结果");return;}model.status=s;repo.saveInspection(model);Ui.toast(this,"状态已更新为："+status(s));render();}
    private void pick(String c){photoCategory=c;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),PICK);}
    private void capture(String c){photoCategory=c;if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},PERMISSION);return;}ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"rectification-"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);startActivityForResult(new Intent(MediaStore.ACTION_IMAGE_CAPTURE).putExtra(MediaStore.EXTRA_OUTPUT,cameraUri),CAMERA);}
    @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)capture(photoCategory);}
    @Override protected void onActivityResult(int r,int ok,Intent d){super.onActivityResult(r,ok,d);if(ok!=RESULT_OK)return;try{if(r==PICK&&d!=null)importPhoto(d.getData());else if(r==CAMERA&&cameraUri!=null){importPhoto(cameraUri);getContentResolver().delete(cameraUri,null,null);}else if(r==PDF&&d!=null){try(OutputStream o=getContentResolver().openOutputStream(d.getData())){new PdfExporter(this).export(List.of(repo.inspection(model.id)),o);}Ui.toast(this,"PDF 已导出");}}catch(Exception e){Ui.toast(this,"操作失败："+e.getMessage());}}
    private void importPhoto(Uri uri)throws Exception{Media m=new MediaService(this).importAndWatermark(uri,model.id,null,photoCategory,model.location,null);repo.addMedia(m);showMedia();Ui.toast(this,"照片已保存并加水印");}
    private void showMedia(){media.removeAllViews();model.media.clear();model.media.addAll(repo.media(model.id));for(Media m:model.media){LinearLayout r=Ui.row(this);ImageView i=new ImageView(this);i.setImageBitmap(BitmapFactory.decodeFile(m.localPath));i.setScaleType(ImageView.ScaleType.CENTER_CROP);r.addView(i,new LinearLayout.LayoutParams(Ui.dp(this,90),Ui.dp(this,72)));r.addView(Ui.text(this,category(m.category),14,false),Ui.weight(1));media.addView(r);}}
    private String status(String s){return switch(s){case"PENDING_RECTIFICATION"->"待整改";case"RECTIFYING"->"整改中";case"RECTIFIED"->"已整改完成";case"COMPLETED"->"已完成";default->"草稿";};}private String result(String s){return"PASS".equals(s)?"合格":"FAIL".equals(s)?"不合格":"不适用";}private String category(String s){return switch(s){case"PROBLEM"->"问题照片";case"RECTIFICATION"->"整改照片";case"RECHECK"->"复查照片";default->"现场照片";};}
}
