package cn.safetyledger.app;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.database.sqlite.SQLiteDatabase;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import cn.safetyledger.app.backup.BackupService;import cn.safetyledger.app.data.LedgerRepository;import cn.safetyledger.app.security.*;import cn.safetyledger.app.sync.*;import java.io.*;import java.util.*;

public final class SettingsActivity extends Activity{
    private static final int EXPORT=801,IMPORT=802;private LedgerRepository repo;private char[]pendingPassword;private BackupService.RestorePackage restore;private Spinner provider;private EditText endpoint,user,secret,token,space,encryption;private TextView syncStatus;
    @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new LedgerRepository(this);render();}
    private void render(){ScrollView sv=new ScrollView(this);LinearLayout root=Ui.column(this);root.setPadding(Ui.dp(this,12),0,Ui.dp(this,12),Ui.dp(this,30));LinearLayout bar=Ui.row(this);bar.setBackgroundColor(Ui.DARK);TextView back=Ui.text(this,"‹",34,true);back.setTextColor(0xffffffff);back.setOnClickListener(v->finish());TextView title=Ui.text(this,"设置",21,true);title.setTextColor(0xffffffff);bar.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,52),Ui.dp(this,56)));bar.addView(title,Ui.weight(1));root.addView(bar);
        root.addView(Ui.text(this,"模板与数据",19,true));Button templates=Ui.button(this,"基础设施 / 检查模板管理");templates.setOnClickListener(v->Ui.start(this,TemplateActivity.class));root.addView(templates);Button trash=Ui.button(this,"回收站");trash.setOnClickListener(v->Ui.start(this,TrashActivity.class));root.addView(trash);
        root.addView(Ui.text(this,"APP 数据备份 / 恢复（不是 PDF）",19,true));LinearLayout data=Ui.row(this);Button out=Ui.button(this,"导出 APP 数据"),in=Ui.button(this,"导入 APP 数据");out.setOnClickListener(v->askPassword(true));in.setOnClickListener(v->askPassword(false));data.addView(out,Ui.weight(1));data.addView(in,Ui.weight(1));root.addView(data);Button migrate=Ui.button(this,"设备迁移");migrate.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("设备迁移").setMessage("旧设备导出 .safetydata → 离线复制 → 新设备导入并选择完整恢复。模板、检查、照片、签名和整改状态会一起迁移。").setPositiveButton("知道了",null).show());root.addView(migrate);
        root.addView(Ui.text(this,"永久删除",19,true));Button pwd=Ui.button(this,"设置 / 修改永久删除密码");pwd.setOnClickListener(v->setDeletePassword());root.addView(pwd);
        root.addView(Ui.text(this,"云同步",19,true));root.addView(Ui.text(this,"已实现可切换 provider 接口、加密配置、连接测试、UUID+版本、同步队列、tombstone、冲突副本和失败通知。自动双向传输/云 A 迁移云 B 尚未实现。",14,false));provider=spinner(new String[]{"WebDAV","Cloudflare","飞牛 NAS / WebDAV","Google Drive","OneDrive","自定义 HTTP 服务器"});endpoint=Ui.input(this,"服务地址 / 账号授权地址");user=Ui.input(this,"用户名");secret=Ui.input(this,"密码");token=Ui.input(this,"Token（可选）");space=Ui.input(this,"同步空间名称");space.setText("safety-ledger");encryption=Ui.input(this,"端到端加密密码");secret.setInputType(0x81);token.setInputType(0x81);encryption.setInputType(0x81);root.addView(provider);root.addView(endpoint);root.addView(user);root.addView(secret);root.addView(token);root.addView(space);root.addView(encryption);syncStatus=Ui.text(this,"同步状态：未配置",15,true);root.addView(syncStatus);LinearLayout syncActions=Ui.row(this);Button test=Ui.button(this,"测试连接"),save=Ui.button(this,"保存并启用"),now=Ui.button(this,"立即同步");test.setOnClickListener(v->testConnection(false));save.setOnClickListener(v->testConnection(true));now.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("后台同步尚未启用").setMessage("本地待同步队列会继续保留，云端传输 provider 尚未完成，因此不会假装同步成功或删除旧云数据。").setPositiveButton("确定",null).show());syncActions.addView(test,Ui.weight(1));syncActions.addView(save,Ui.weight(1));syncActions.addView(now,Ui.weight(1));root.addView(syncActions);loadProvider();
        root.addView(Ui.text(this,"六个月归档 / 本地媒体",19,true));root.addView(Ui.text(this,"数据库已预留归档 PDF 索引。只有“已完成 + 云端已验证”的记录才允许成为 180 天清理候选；未整改完成的记录永不自动归档清理。当前 provider 尚未完成，故自动释放保持关闭，避免丢失原始资料。",14,false));sv.addView(root);setContentView(sv);}
    private Spinner spinner(String[]v){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,v));return s;}
    private void loadProvider(){try(Cursor c=repo.raw().rawQuery("SELECT provider_type,endpoint,username,encrypted_secret,token_ciphertext,sync_space,encryption_secret FROM sync_providers WHERE enabled=1 LIMIT 1",null)){if(c.moveToFirst()){String type=c.getString(0);for(int i=0;i<provider.getCount();i++)if(provider.getItemAtPosition(i).equals(type))provider.setSelection(i);endpoint.setText(c.getString(1));user.setText(c.getString(2));SecretStore s=new SecretStore();secret.setText(s.decrypt(c.getString(3)));token.setText(s.decrypt(c.getString(4)));space.setText(c.getString(5));encryption.setText(s.decrypt(c.getString(6)));syncStatus.setText("同步状态：待同步（provider 传输尚未启用）");}}catch(Exception e){syncStatus.setText("同步状态：配置读取失败");}}
    private void askPassword(boolean export){EditText p=Ui.input(this,"备份密码（至少 8 位）");p.setInputType(0x81);new AlertDialog.Builder(this).setTitle(export?"导出 APP 数据":"导入 APP 数据").setMessage(export?"密码无法找回，请妥善保管。":"请选择 .safetydata 文件，PDF 不可导入。").setView(p).setPositiveButton("继续",(d,w)->{pendingPassword=p.getText().toString().toCharArray();if(pendingPassword.length<8){Ui.toast(this,"密码至少 8 位");return;}Intent i=export?new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").putExtra(Intent.EXTRA_TITLE,"安全检查台账-"+System.currentTimeMillis()+".safetydata"):new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,export?EXPORT:IMPORT);}).setNegativeButton("取消",null).show();}
    @Override protected void onActivityResult(int r,int ok,Intent d){super.onActivityResult(r,ok,d);if(ok!=RESULT_OK||d==null||pendingPassword==null)return;if(r==EXPORT)doExport(d.getData());else if(r==IMPORT)doImport(d.getData());}
    private void doExport(Uri u){try(OutputStream o=getContentResolver().openOutputStream(u)){new BackupService(this).exportData(o,pendingPassword);Ui.toast(this,"APP 数据已加密导出");}catch(Exception e){Ui.toast(this,"导出失败："+e.getMessage());}finally{pendingPassword=null;}}
    private void doImport(Uri u){try(InputStream in=getContentResolver().openInputStream(u)){restore=new BackupService(this).decryptAndValidate(in,pendingPassword);new AlertDialog.Builder(this).setTitle("选择恢复方式").setItems(new String[]{"合并恢复（保留本机数据，不覆盖冲突）","完整恢复（替换本机数据）"},(d,which)->{try{BackupService b=new BackupService(this);if(which==0){int n=b.mergeRestore(restore);Ui.toast(this,"合并恢复完成，新增 "+n+" 条；冲突已保留副本");}else{b.fullRestore(restore);Ui.toast(this,"完整恢复完成，请重新启动 APP");new Handler(Looper.getMainLooper()).postDelayed(()->{finishAffinity();System.exit(0);},1000);}}catch(Exception e){Ui.toast(this,"恢复失败："+e.getMessage());}}).setOnCancelListener(d->{if(restore!=null)restore.close();}).show();}catch(Exception e){Ui.toast(this,"导入失败："+e.getMessage());}finally{pendingPassword=null;}}
    private void setDeletePassword(){EditText p=Ui.input(this,"新密码（至少 6 位）");p.setInputType(0x81);new AlertDialog.Builder(this).setTitle("永久删除密码").setView(p).setPositiveButton("保存",(d,w)->{char[]x=p.getText().toString().toCharArray();if(x.length<6){Ui.toast(this,"密码至少 6 位");return;}try{repo.putSetting("delete_password_hash",PasswordHash.create(x));Ui.toast(this,"永久删除密码已设置");}catch(Exception e){Ui.toast(this,"密码设置失败");}}).setNegativeButton("取消",null).show();}
    private void testConnection(boolean saveOnSuccess){String t=(String)provider.getSelectedItem(),url=endpoint.getText().toString().trim(),u=user.getText().toString().trim(),pw=secret.getText().toString(),tk=token.getText().toString();syncStatus.setText("同步状态：正在测试…");new Thread(()->{SyncProvider.ConnectionResult r=new HttpSyncProvider(t.contains("WebDAV")?"WebDAV":"HTTP").test(Map.of("endpoint",url,"username",u,"secret",pw,"token",tk));runOnUiThread(()->{if(r.success()){syncStatus.setText("同步状态：连接成功"+(saveOnSuccess?"，配置已启用":""));if(saveOnSuccess)saveProvider(t,url,u,pw,tk);new AlertDialog.Builder(this).setTitle("连接成功").setMessage(r.message()).setPositiveButton("确定",null).show();}else{syncStatus.setText("同步状态：失败 · "+r.message());syncNotification(r.message());new AlertDialog.Builder(this).setTitle("连接失败").setMessage(r.message()).setPositiveButton("确定",null).show();}});}).start();}
    private void saveProvider(String type,String url,String u,String pw,String tk){try{SecretStore s=new SecretStore();SQLiteDatabase d=repo.raw();long n=System.currentTimeMillis();d.execSQL("UPDATE sync_providers SET enabled=0");d.execSQL("INSERT INTO sync_providers(id,provider_type,display_name,endpoint,username,encrypted_secret,token_ciphertext,sync_space,encryption_secret,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",new Object[]{UUID.randomUUID().toString(),type,type,url,u,s.encrypt(pw),s.encrypt(tk),space.getText().toString().trim(),s.encrypt(encryption.getText().toString()),1,n,n});}catch(Exception e){syncStatus.setText("同步状态：配置加密保存失败");Ui.toast(this,"配置保存失败："+e.getMessage());}}
    private void syncNotification(String message){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},991);Notification n=new Notification.Builder(this,SafetyLedgerApp.SYNC_CHANNEL).setSmallIcon(R.drawable.ic_app).setContentTitle("安全检查台账同步失败").setContentText(message).setAutoCancel(true).build();getSystemService(NotificationManager.class).notify(1001,n);}
}
