package cn.safetyledger.app;

import android.app.*;import android.os.Bundle;import android.view.*;import android.widget.*;import cn.safetyledger.app.data.Entities.*;import cn.safetyledger.app.data.LedgerRepository;import java.util.*;

public final class TemplateActivity extends Activity{
    private LedgerRepository repo;private LinearLayout list;private String selectedId;
    @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new LedgerRepository(this);render();}
    private void render(){LinearLayout root=Ui.column(this);LinearLayout bar=Ui.row(this);bar.setBackgroundColor(Ui.DARK);TextView back=Ui.text(this,"‹",34,true);back.setTextColor(0xffffffff);back.setOnClickListener(v->finish());TextView title=Ui.text(this,"检查模板管理",21,true);title.setTextColor(0xffffffff);bar.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,52),Ui.dp(this,56)));bar.addView(title,Ui.weight(1));root.addView(bar);Button add=Ui.button(this,"新建模板");add.setOnClickListener(v->editTemplate(null));root.addView(add);ScrollView sv=new ScrollView(this);list=Ui.column(this);list.setPadding(Ui.dp(this,10),Ui.dp(this,8),Ui.dp(this,10),Ui.dp(this,20));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);showList();}
    private void showList(){list.removeAllViews();for(Template t:repo.templates(true)){LinearLayout box=Ui.column(this);box.setBackground(Ui.border(this,t.active?Ui.TEAL:0xff94a3b8));box.addView(Ui.text(this,t.name+" · "+t.category+(t.active?"":"（已停用）"),18,true));LinearLayout a=Ui.row(this);Button edit=Ui.button(this,"名称/类别");Button toggle=Ui.button(this,t.active?"停用":"启用");Button item=Ui.button(this,"管理检查项");Button delete=Ui.button(this,"删除");edit.setOnClickListener(v->editTemplate(t));toggle.setOnClickListener(v->{repo.saveTemplate(t.id,t.name,t.category,!t.active);showList();});item.setOnClickListener(v->showItems(t));delete.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("删除基础设施/模板").setMessage("模板将不再用于新检查，历史检查快照保持原样，可继续查看和导出。").setPositiveButton("删除",(d,w)->{repo.deleteTemplate(t.id);showList();}).setNegativeButton("取消",null).show());a.addView(edit,Ui.weight(1));a.addView(toggle,Ui.weight(1));a.addView(item,Ui.weight(1));a.addView(delete,Ui.weight(1));box.addView(a);list.addView(box);list.addView(Ui.gap(this,8));}}
    private void editTemplate(Template t){LinearLayout l=Ui.column(this);EditText name=Ui.input(this,"模板名称");EditText cat=Ui.input(this,"模板类别");if(t!=null){name.setText(t.name);cat.setText(t.category);}l.addView(name);l.addView(cat);new AlertDialog.Builder(this).setTitle(t==null?"新建模板":"编辑模板").setView(l).setPositiveButton("保存",(d,w)->{String n=name.getText().toString().trim(),c=cat.getText().toString().trim();if(n.isBlank()||c.isBlank()){Ui.toast(this,"名称和类别不能为空");return;}repo.saveTemplate(t==null?null:t.id,n,c,t==null||t.active);if(t==null)repo.putSetting("current_draft","");showList();}).setNegativeButton("取消",null).show();}
    private void showItems(Template t){selectedId=t.id;list.removeAllViews();Button back=Ui.button(this,"‹ 返回模板列表");back.setOnClickListener(v->showList());list.addView(back);list.addView(Ui.text(this,t.name+" · 检查项目",20,true));Button add=Ui.button(this,"新增检查项目");add.setOnClickListener(v->editItem(t,null));list.addView(add);for(TemplateItem x:repo.templateItems(t.id)){LinearLayout box=Ui.column(this);box.setBackground(Ui.border(this,0xffcbd5e1));box.addView(Ui.text(this,x.order+". "+x.category,17,true));box.addView(Ui.text(this,x.content+"\n标准："+x.standard,14,false));LinearLayout a=Ui.row(this);for(String[]op:new String[][]{{"编辑","E"},{"上移","U"},{"下移","D"},{"删除","X"}}){Button b=Ui.button(this,op[0]);b.setOnClickListener(v->{switch(op[1]){case"E"->editItem(t,x);case"U"->{repo.reorderItem(t.id,x.id,-1);showItems(repo.template(t.id));}case"D"->{repo.reorderItem(t.id,x.id,1);showItems(repo.template(t.id));}case"X"->new AlertDialog.Builder(this).setMessage("删除此检查项目？历史记录不会受影响。").setPositiveButton("删除",(q,z)->{repo.deleteTemplateItem(x.id);showItems(repo.template(t.id));}).setNegativeButton("取消",null).show();}});a.addView(b,Ui.weight(1));}box.addView(a);list.addView(box);list.addView(Ui.gap(this,6));}}
    private void editItem(Template t,TemplateItem x){LinearLayout l=Ui.column(this);EditText cat=Ui.input(this,"检查类别"),content=Ui.input(this,"检查内容"),standard=Ui.input(this,"检查标准");if(x!=null){cat.setText(x.category);content.setText(x.content);standard.setText(x.standard);}l.addView(cat);l.addView(content);l.addView(standard);new AlertDialog.Builder(this).setTitle(x==null?"新增检查项目":"编辑检查项目").setView(l).setPositiveButton("保存",(d,w)->{int order=x==null?repo.templateItems(t.id).size()+1:x.order;repo.saveTemplateItem(x==null?null:x.id,t.id,cat.getText().toString().trim(),content.getText().toString().trim(),standard.getText().toString().trim(),order);showItems(repo.template(t.id));}).setNegativeButton("取消",null).show();}
    @Override public void onBackPressed(){if(selectedId!=null){selectedId=null;showList();}else super.onBackPressed();}
}
