package cn.safetyledger.app;

import android.app.Activity;import android.app.AlertDialog;import android.os.Bundle;import android.text.InputType;import android.text.method.PasswordTransformationMethod;import android.widget.*;
import cn.safetyledger.app.data.Entities.Inspection;import cn.safetyledger.app.data.LedgerRepository;import cn.safetyledger.app.media.MediaService;import cn.safetyledger.app.sync.CloudSyncService;import cn.safetyledger.app.sync.SyncErrorFormatter;
import java.text.DateFormat;import java.util.*;

public final class TrashActivity extends Activity{
    private LedgerRepository repo;private LinearLayout list;private CloudSyncService cloud;
    @Override protected void onCreate(Bundle state){super.onCreate(state);Ui.setupWindow(this);repo=new LedgerRepository(this);cloud=new CloudSyncService(this);LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.BG);root.addView(Ui.appBar(this,"回收站"));ScrollView scroll=new ScrollView(this);list=Ui.column(this);list.setPadding(Ui.dp(this,12),Ui.dp(this,10),Ui.dp(this,12),Ui.dp(this,24));scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);load();}
    private void load(){list.removeAllViews();TextView note=Ui.text(this,"普通删除只进入本机回收站，可直接恢复。启用云同步后，永久删除统一验证云同步空间密码，并写入轻量云端回收站指令；其他设备无需等待整包照片同步即可处理删除。云端回收站保留30天。",13,false);note.setTextColor(Ui.MUTED);list.addView(note);list.addView(Ui.gap(this,8));if(isAdmin()&&cloud.hasConfiguredSync()){Button recovery=Ui.secondaryButton(this,"云端回收站 · 管理员查看和恢复");recovery.setOnClickListener(v->loadAdminRecovery());list.addView(recovery);list.addView(Ui.gap(this,10));}int count=0;for(Inspection inspection:repo.list(null,null,null,true,1,100000).rows){count++;LinearLayout card=Ui.card(this);card.setPadding(Ui.dp(this,12),Ui.dp(this,9),Ui.dp(this,12),Ui.dp(this,9));card.addView(Ui.text(this,inspection.date+" "+inspection.time+" · "+inspection.templateName+"\n"+inspection.location,15,true));LinearLayout actions=Ui.row(this);Button restore=Ui.compactButton(this,"恢复记录",true);Button delete=Ui.dangerButton(this,"永久删除");restore.setOnClickListener(v->{repo.restore(inspection.id);Ui.toast(this,"记录已恢复");load();});delete.setOnClickListener(v->confirm(inspection));actions.addView(restore,Ui.weight(1));actions.addView(Ui.horizontalGap(this,6));actions.addView(delete,Ui.weight(1));card.addView(actions);list.addView(card);list.addView(Ui.gap(this,8));}if(count==0){TextView empty=Ui.text(this,"本机回收站为空",16,true);empty.setTextColor(Ui.MUTED);empty.setGravity(android.view.Gravity.CENTER);list.addView(empty);}}
    private boolean isAdmin(){String r=repo.setting("cloud_role","");return "OWNER".equals(r)||"ADMIN".equals(r)||"PRIMARY".equals(repo.setting("device_role",""));}
    private void confirm(Inspection inspection){if(!cloud.hasConfiguredSync()){new AlertDialog.Builder(this).setTitle("仅永久删除本机记录？").setMessage("当前没有启用云同步，因此不会建立云端30天恢复副本，也不会通知其他设备。确定只永久删除本机这条记录吗？").setPositiveButton("仅删除本机",(d,w)->{new MediaService(this).deleteInspectionMedia(inspection.id);repo.permanentDelete(inspection.id);Ui.toast(this,"本机记录已永久删除");load();}).setNegativeButton("取消",null).show();return;}EditText password=Ui.input(this,"请输入云同步空间密码");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);password.setTransformationMethod(PasswordTransformationMethod.getInstance());new AlertDialog.Builder(this).setTitle("移入云端回收站").setMessage("密码验证成功后，本条记录会进入云端回收站并保留30天。其他设备接收到轻量删除指令后会自动删除本地对应记录；管理员30天内仍可恢复。").setView(password).setPositiveButton("确认永久删除",(d,w)->deleteWithCloudRecovery(inspection,password.getText().toString().toCharArray())).setNegativeButton("取消",null).show();}
    private void deleteWithCloudRecovery(Inspection inspection,char[] password){Ui.toast(this,"正在验证密码并写入云端回收站…");new Thread(()->{try{cloud.archiveAndPermanentlyDelete(inspection.id,password,null);runOnUiThread(()->{Ui.toast(this,"已删除；云端回收站保留30天");load();});}catch(Exception error){String msg=SyncErrorFormatter.format(error);runOnUiThread(()->new AlertDialog.Builder(this).setTitle(SyncErrorFormatter.isNetwork(error)?"网络连接问题":"删除失败").setMessage(msg).setPositiveButton("确定",null).show());}},"trash-cloud-delete").start();}
    private void loadAdminRecovery(){Ui.toast(this,"正在读取云端回收站…");new Thread(()->{try{List<CloudSyncService.RecoveryEntry> entries=cloud.listAdminRecovery();runOnUiThread(()->showRecovery(entries));}catch(Exception error){String msg=SyncErrorFormatter.format(error);runOnUiThread(()->new AlertDialog.Builder(this).setTitle(SyncErrorFormatter.isNetwork(error)?"网络连接问题":"读取失败").setMessage(msg).setPositiveButton("确定",null).show());}},"admin-recovery-list").start();}
    private void showRecovery(List<CloudSyncService.RecoveryEntry> entries){if(entries.isEmpty()){Ui.toast(this,"云端回收站为空");return;}LinearLayout box=Ui.column(this);for(CloudSyncService.RecoveryEntry e:entries){String when=e.deletedAt()>0?DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(e.deletedAt())):"未知时间";String expire=e.expiresAt()>0?"\n自动清空："+DateFormat.getDateInstance(DateFormat.SHORT).format(new Date(e.expiresAt())):"";String title=(e.date().isBlank()?"":e.date()+" "+e.time()+" · ")+e.templateName()+"\n"+(e.location().isBlank()?"地点未知":e.location())+"\n删除时间："+when+expire;Button b=Ui.secondaryButton(this,title);b.setGravity(android.view.Gravity.START|android.view.Gravity.CENTER_VERTICAL);b.setOnClickListener(v->confirmRecovery(e));box.addView(b);box.addView(Ui.gap(this,6));}ScrollView s=new ScrollView(this);s.addView(box);s.setLayoutParams(new android.view.ViewGroup.LayoutParams(-1,Ui.dp(this,460)));new AlertDialog.Builder(this).setTitle("云端回收站").setView(s).setNegativeButton("关闭",null).show();}
    private void confirmRecovery(CloudSyncService.RecoveryEntry entry){String detail=(entry.date().isBlank()?"":entry.date()+" "+entry.time()+"\n")+entry.templateName()+"\n"+(entry.location().isBlank()?"地点未知":entry.location())+"\n\n恢复后，管理员设备会立即重新发布该检查记录；其他设备收到“恢复指令”后会自动安排检查内容同步。";new AlertDialog.Builder(this).setTitle("恢复这条检查记录？").setMessage(detail).setPositiveButton("恢复",(d,w)->new Thread(()->{try{cloud.restoreAdminRecovery(entry.name());runOnUiThread(()->{Ui.toast(this,"已恢复并发布到云端");load();});}catch(Exception error){String msg=SyncErrorFormatter.format(error);runOnUiThread(()->new AlertDialog.Builder(this).setTitle(SyncErrorFormatter.isNetwork(error)?"网络连接问题":"恢复失败").setMessage(msg).setPositiveButton("确定",null).show());}},"admin-recovery-restore").start()).setNegativeButton("取消",null).show();}
}
