plugins { id 'com.android.application' }

android {
    namespace 'cn.safetyledger.app'
    compileSdk 35

    defaultConfig {
        applicationId 'cn.safetyledger.app'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '1.2.2'
        testInstrumentationRunner 'android.app.InstrumentationTestRunner'
    }
    buildTypes {
        debug { applicationIdSuffix '' }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint { abortOnError true; checkReleaseBuilds true }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
