FROM node:22-alpine

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY schema.sql wrangler.fnos.jsonc ./
COPY src ./src
COPY docker-start-fnos.sh ./

EXPOSE 8787
VOLUME ["/data"]
CMD ["sh", "/app/docker-start-fnos.sh"]
