package cn.safetyledger.app.backup;

import android.content.*;import android.database.Cursor;import android.database.sqlite.SQLiteDatabase;import android.os.*;import cn.safetyledger.app.SafetyLedgerApp;import cn.safetyledger.app.data.LedgerDatabase;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.*;import java.util.*;import java.util.zip.*;import javax.crypto.*;import javax.crypto.spec.*;

public final class BackupService{
    private static final byte[] MAGIC="SAFETYDATA".getBytes(StandardCharsets.US_ASCII);private static final int FORMAT=1,ITERATIONS=310000;
    private final Context context;public BackupService(Context c){context=c.getApplicationContext();}
    public void exportData(OutputStream destination,char[]password)throws Exception{if(password.length<8)throw new IllegalArgumentException("密码至少 8 位");File tmp=File.createTempFile("safety-backup-",".zip",context.getCacheDir());try{LedgerDatabase h=((SafetyLedgerApp)context).db();SQLiteDatabase db=h.getWritableDatabase();db.rawQuery("PRAGMA wal_checkpoint(FULL)",null).close();File dbFile=context.getDatabasePath(LedgerDatabase.NAME);Properties manifest=new Properties();manifest.setProperty("format","safetydata");manifest.setProperty("formatVersion","1");manifest.setProperty("schemaVersion",String.valueOf(LedgerDatabase.VERSION));manifest.setProperty("createdAt",String.valueOf(System.currentTimeMillis()));manifest.setProperty("databaseSha256",sha(dbFile));try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(tmp))){entry(z,"manifest.properties",properties(manifest));file(z,"database.sqlite",dbFile);File media=new File(context.getFilesDir(),"business_media");zipDir(z,media,"business_media/");}encrypt(tmp,destination,password);}finally{tmp.delete();Arrays.fill(password,'\0');}}
    public RestorePackage decryptAndValidate(InputStream source,char[]password)throws Exception{File zip=File.createTempFile("safety-restore-",".zip",context.getCacheDir());File dir=new File(context.getCacheDir(),"restore-"+UUID.randomUUID());if(!dir.mkdirs())throw new IOException("无法创建恢复目录");try{decrypt(source,zip,password);unzip(zip,dir);File manifestFile=new File(dir,"manifest.properties"),dbFile=new File(dir,"database.sqlite");if(!manifestFile.isFile()||!dbFile.isFile())throw new IOException("备份内容不完整");Properties m=new Properties();try(InputStream in=new FileInputStream(manifestFile)){m.load(in);}if(!"safetydata".equals(m.getProperty("format")))throw new IOException("不是 APP 数据备份");if(Integer.parseInt(m.getProperty("formatVersion","0"))>FORMAT)throw new IOException("备份格式版本过新");if(Integer.parseInt(m.getProperty("schemaVersion","0"))>LedgerDatabase.VERSION)throw new IOException("数据库版本过新，请先升级 APP");if(!sha(dbFile).equals(m.getProperty("databaseSha256")))throw new IOException("数据库完整性校验失败");SQLiteDatabase test=SQLiteDatabase.openDatabase(dbFile.getAbsolutePath(),null,SQLiteDatabase.OPEN_READONLY);try(Cursor c=test.rawQuery("SELECT max(version) FROM schema_migrations",null)){if(!c.moveToFirst()||c.getInt(0)<1)throw new IOException("数据库迁移元数据无效");}finally{test.close();}return new RestorePackage(dir,dbFile);}catch(Exception e){deleteTree(dir);throw e;}finally{zip.delete();Arrays.fill(password,'\0');}}
    public void fullRestore(RestorePackage p)throws Exception{SafetyLedgerApp app=(SafetyLedgerApp)context;app.db().close();File target=context.getDatabasePath(LedgerDatabase.NAME);File recovery=new File(target.getParentFile(),LedgerDatabase.NAME+".before-restore");if(target.exists())Files.copy(target.toPath(),recovery.toPath(),StandardCopyOption.REPLACE_EXISTING);Files.copy(p.database.toPath(),target.toPath(),StandardCopyOption.REPLACE_EXISTING);new File(target+"-wal").delete();new File(target+"-shm").delete();File mediaRoot=new File(context.getFilesDir(),"business_media");deleteTree(mediaRoot);copyMedia(new File(p.root,"business_media"),mediaRoot);try(SQLiteDatabase restored=SQLiteDatabase.openDatabase(target.getAbsolutePath(),null,SQLiteDatabase.OPEN_READWRITE)){normalizeMediaPaths(restored);}p.close();}
    public int mergeRestore(RestorePackage p)throws Exception{LedgerDatabase h=((SafetyLedgerApp)context).db();SQLiteDatabase d=h.getWritableDatabase();String path=p.database.getAbsolutePath().replace("'","''");int inserted=0;String[] tables={"templates","template_items","inspections","inspection_items","media","signatures","app_settings","sync_providers","tombstones","archive_index","holiday_cache"};d.execSQL("ATTACH DATABASE '"+path+"' AS incoming");d.beginTransaction();try{for(String table:tables){Set<String>cols=columns(d,table);String names=String.join(",",cols);d.execSQL("INSERT OR IGNORE INTO main."+table+"("+names+") SELECT "+names+" FROM incoming."+table);try(Cursor c=d.rawQuery("SELECT changes()",null)){if(c.moveToFirst())inserted+=c.getInt(0);}if(!"app_settings".equals(table)&&cols.contains("updated_at")&&cols.contains("revision")){d.execSQL("INSERT OR IGNORE INTO conflict_copies(id,entity_type,entity_id,local_revision,remote_revision,payload_json,created_at) SELECT lower(hex(randomblob(16))),?,m.id,COALESCE(m.revision,1),COALESCE(i.revision,1),'{}',? FROM main."+table+" m JOIN incoming."+table+" i ON m.id=i.id WHERE COALESCE(m.updated_at,0)<>COALESCE(i.updated_at,0)",new Object[]{table,System.currentTimeMillis()});}}d.setTransactionSuccessful();}finally{d.endTransaction();d.execSQL("DETACH DATABASE incoming");}copyMedia(new File(p.root,"business_media"),new File(context.getFilesDir(),"business_media"));normalizeMediaPaths(d);p.close();return inserted;}
    private void normalizeMediaPaths(SQLiteDatabase d){File root=new File(context.getFilesDir(),"business_media");try(Cursor c=d.rawQuery("SELECT id,inspection_id FROM media WHERE deleted_at IS NULL",null)){while(c.moveToNext()){File f=new File(new File(root,c.getString(1)),c.getString(0)+".jpg");if(f.isFile())d.execSQL("UPDATE media SET local_path=? WHERE id=?",new Object[]{f.getAbsolutePath(),c.getString(0)});}}try(Cursor c=d.rawQuery("SELECT id,inspection_id,role FROM signatures WHERE deleted_at IS NULL",null)){while(c.moveToNext()){File f=new File(new File(root,c.getString(1)),"signature-"+c.getString(2)+".png");if(f.isFile())d.execSQL("UPDATE signatures SET local_path=? WHERE id=?",new Object[]{f.getAbsolutePath(),c.getString(0)});}}}
    private Set<String> columns(SQLiteDatabase d,String t){Set<String>s=new LinkedHashSet<>();try(Cursor c=d.rawQuery("PRAGMA main.table_info("+t+")",null)){while(c.moveToNext())s.add(c.getString(1));}return s;}
    private void encrypt(File plain,OutputStream out,char[]pw)throws Exception{byte[]salt=random(16),iv=random(12);SecretKey key=derive(pw,salt);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key,new GCMParameterSpec(128,iv));out.write(MAGIC);out.write(FORMAT);out.write(salt);out.write(iv);try(CipherOutputStream co=new CipherOutputStream(out,c)){Files.copy(plain.toPath(),co);}}
    private void decrypt(InputStream in,File out,char[]pw)throws Exception{byte[]magic=readExactly(in,MAGIC.length);if(!Arrays.equals(magic,MAGIC))throw new IOException("文件不是 .safetydata APP 数据备份（PDF 不可导入）");int version=in.read();if(version<1||version>FORMAT)throw new IOException("不支持的备份格式版本");byte[]salt=readExactly(in,16),iv=readExactly(in,12);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,derive(pw,salt),new GCMParameterSpec(128,iv));try(CipherInputStream ci=new CipherInputStream(in,c);OutputStream o=new FileOutputStream(out)){copy(ci,o);}catch(IOException e){throw new SecurityException("密码错误或备份完整性校验失败",e);}}
    private SecretKey derive(char[]pw,byte[]salt)throws Exception{PBEKeySpec s=new PBEKeySpec(pw,salt,ITERATIONS,256);byte[]k=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(s).getEncoded();s.clearPassword();return new SecretKeySpec(k,"AES");}
    private byte[]random(int n){byte[]b=new byte[n];new SecureRandom().nextBytes(b);return b;}private byte[]properties(Properties p)throws IOException{ByteArrayOutputStream b=new ByteArrayOutputStream();p.store(b,"Safety Ledger portable backup");return b.toByteArray();}
    private void entry(ZipOutputStream z,String name,byte[]b)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(b);z.closeEntry();}private void file(ZipOutputStream z,String name,File f)throws IOException{z.putNextEntry(new ZipEntry(name));Files.copy(f.toPath(),z);z.closeEntry();}private void zipDir(ZipOutputStream z,File dir,String prefix)throws IOException{if(!dir.isDirectory())return;File[]fs=dir.listFiles();if(fs==null)return;for(File f:fs)if(f.isDirectory())zipDir(z,f,prefix+f.getName()+"/");else file(z,prefix+f.getName(),f);}
    private void unzip(File zip,File dir)throws IOException{try(ZipInputStream z=new ZipInputStream(new FileInputStream(zip))){for(ZipEntry e;(e=z.getNextEntry())!=null;){File out=new File(dir,e.getName()).getCanonicalFile();if(!out.toPath().startsWith(dir.getCanonicalFile().toPath()))throw new IOException("备份路径非法");if(e.isDirectory())out.mkdirs();else{out.getParentFile().mkdirs();try(OutputStream o=new FileOutputStream(out)){copy(z,o);}}}}}
    private static byte[] readExactly(InputStream in,int length)throws IOException{byte[]out=new byte[length];int offset=0;while(offset<length){int n=in.read(out,offset,length-offset);if(n<0)throw new EOFException("备份文件被截断");offset+=n;}return out;}
    private static void copy(InputStream in,OutputStream out)throws IOException{byte[]b=new byte[65536];for(int n;(n=in.read(b))>=0;)if(n>0)out.write(b,0,n);}
    private void copyMedia(File from,File to)throws IOException{if(!from.exists())return;Files.walk(from.toPath()).forEach(p->{try{Path rel=from.toPath().relativize(p),dest=to.toPath().resolve(rel);if(Files.isDirectory(p))Files.createDirectories(dest);else if(!Files.exists(dest))Files.copy(p,dest);}catch(IOException e){throw new UncheckedIOException(e);}});}
    private String sha(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream i=new FileInputStream(f)){byte[]b=new byte[65536];for(int n;(n=i.read(b))>0;)d.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte x:d.digest())s.append(String.format("%02x",x));return s.toString();}
    private static void deleteTree(File f){if(f.isDirectory()){File[]a=f.listFiles();if(a!=null)for(File x:a)deleteTree(x);}f.delete();}
    public static final class RestorePackage implements AutoCloseable{public final File root,database;RestorePackage(File r,File d){root=r;database=d;}public void close(){deleteTree(root);}}
}
